### PR TITLE
feat: add function to detect qos

### PR DESCRIPTION
**Pull request by wep21**
This feature enables to detect qos of image and overlays automatically, so 
the image which has best effort qos can be shown in the viewer.
```
❯ ros2 topic info -v /image_raw

Type: sensor_msgs/msg/Image

Publisher count: 1

Node name: usb_cam
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 03.49.10.01.14.53.a4.f5.3f.dc.00.77.00.00.17.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  Durability: VOLATILE
  Lifespan: 9223372036854775807 nanoseconds
  Deadline: 9223372036854775807 nanoseconds
  Liveliness: AUTOMATIC
  Liveliness lease duration: 9223372036854775807 nanoseconds

Subscription count: 1

Node name: rqt_gui_cpp_node_71541
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 96.46.10.01.1c.5e.c3.d1.5b.c2.d0.c9.00.00.16.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  Durability: VOLATILE
  Lifespan: 9223372036854775807 nanoseconds
  Deadline: 9223372036854775807 nanoseconds
  Liveliness: AUTOMATIC
  Liveliness lease duration: 9223372036854775807 nanoseconds
```

### CODE REVIEW

**Comment by wep21** [comment]
FYI @ijnek

**Comment by ijnek** [comment]
@wep21 Thank you for your contribution.

I'm wondering, if the aim of this PR is to simply get BEST_EFFORT subscription working, would simply changing the qos profile to **rmw_qos_profile_sensor_data** be enough?

ie. Changing
```
subscriber = it.subscribe(topic.toStdString(), 1, &ImageManager::callbackImage, this, &hints);
```
to
```
subscriber = image_transport::create_subscription(
        node.get(), topic.toStdString(),
        std::bind(&ImageManager::callbackImage, this, std::placeholders::_1),
        transport.toStdString(), rmw_qos_profile_sensor_data);
```

``ros2 topic info -v /image_raw`` with this change returns:

```
Type: sensor_msgs/msg/Image

Publisher count: 0

Subscription count: 1

Node name: rqt_gui_cpp_node_561693
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 3a.7c.10.01.07.bb.cd.8b.f2.4a.19.30.00.00.15.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  Durability: VOLATILE
  Lifespan: 9223372036854775807 nanoseconds
  Deadline: 9223372036854775807 nanoseconds
  Liveliness: AUTOMATIC
  Liveliness lease duration: 9223372036854775807 nanoseconds
```

domain_bridge seems to use the try_discover_source code to handle cases where multiple publishers are publishing on the same topic with different qos, but I'm guessing that's not what you're trying to solve here?

**Comment by wep21** [comment]
> I'm wondering, if the aim of this PR is to simply get BEST_EFFORT subscription working, would simply changing the qos profile to rmw_qos_profile_sensor_data be enough?

Yes, it's enough to handle only `best_effort` case.

> domain_bridge seems to use the try_discover_source code to handle cases where multiple publishers are publishing on the same topic with different qos, but I'm guessing that's not what you're trying to solve here?

The most common usecase for image is to use `best effort` reliability because the data size of the image can be huge.
However, I think it's better to handle some minor cases you mentioned above.

**Comment by ijnek** [comment]
#3 has the proposed changes, would you be able to review?

*rmw_qos_profile_sensor_data* should be able to handle both reliable and best-effort topics(table below from [About Quality of Service Settings](https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html))

<p style="box-sizing: border-box; line-height: 24px; font-size: 16px; margin: 0px 0px 24px; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><em style="box-sizing: border-box;">Compatibility of reliability QoS policies:</em></p><div class="wy-table-responsive" style="box-sizing: border-box; margin-bottom: 24px; max-width: 100%; overflow: auto; color: rgb(64, 64, 64); font-family: Lato, proxima-nova, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(252, 252, 252); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Publisher | Subscription | Compatible
-- | -- | --
Best effort | Best effort | Yes
Best effort | Reliable | No
Reliable | Best effort | Yes
Reliable | Reliable | Yes

</div>

I think handling multiple publishers with different qos on the same topic is something that doesn't have to be handled, because I can't think of a case where there is more than one publisher for an image on a topic.

**Comment by wep21** [comment]
Alright, move to #3

**Pull request closed without merging**
