### PR TITLE
feat: support compressed image

### PR DESCRIPTION
**Pull request by wep21**
This PR enables to show compressed image topic in the viewer.

### CODE REVIEW

**Comment by wep21** [comment]
FYI @ijnek

**Comment by ijnek** [comment]
@wep21 Thank you for your contribution! Compressed image transport would be a good feature addition.

Running your branch, I get the following warning:
```
[WARN] [1645234402.244835294] [rqt_gui_cpp_node_355076]: [image_transport] It looks like you are trying to subscribe directly to a transport-specific image topic '/image_raw/compressed', in which case you will likely get a connection error. Try subscribing to the base topic '/image_raw' instead with parameter ~image_transport set to 'compressed' (on the command line, _image_transport:=compressed). See http://ros.org/wiki/image_transport for details.
```

Rather than subscribing to `image_raw/compressed` with `raw` transport, I think image_transport needs a subscription to `image_raw` with `compressed` transport.

Before fixing up those in this PR though, I'd like to suggest adding another combobox as shown below to list the available transports, (eg. "Raw", "Compressed", "Theora", etc...).

Screenshot from 2022-02-19 10-53-06

Happy to hear your thoughts! I'm happy to implement this.

**Comment by wep21** [comment]
@ijnek 
> Rather than subscribing to image_raw/compressed with raw transport, I think image_transport needs a subscription to image_raw with compressed transport.

This is because topic name("image_raw/compressed") is directly saved, but transport separated topic string("image_raw compressed") should be saved. I fixed it in https://github.com/ros-sports/rqt_image_overlay/pull/6/commits/53859f86c26a51a64f9090308626aef2408d55f4.

> Before fixing up those in this PR though, I'd like to suggest adding another combobox as shown below to list the available transports, (eg. "Raw", "Compressed", "Theora", etc...).

I think the current implementation is better than the one you suggested in terms of user interface because a user can show 
all the topic candidates including any transports in the combo box once in the former, while a user have to select a base image topic first to know which transport candidate exists in the latter.

**Comment by wep21** [comment]
I referred to `rqt_image_view` to implement this.
https://github.com/ros-visualization/rqt_image_view/blob/5844d958d6ce3265c2185256adaea264974b0f5c/src/rqt_image_view/image_view.cpp#L194-L222
https://github.com/ros-visualization/rqt_image_view/blob/5844d958d6ce3265c2185256adaea264974b0f5c/src/rqt_image_view/image_view.cpp#L237-L285

**Comment by ijnek** [comment]
This PR has me thinking and investigating quite a bit!

> I think the current implementation is better than the one you suggested in terms of user interface 

As you say, it may be easier to see the original way. I think we should use brackets or separate by space, rather than a slash. ComboBox items could look like:

```
image_raw (raw)
image_raw (compressed)
image_raw (theora)
...
```

Now, about the changes, I understand that the code is a port from `rqt_image_view`, but I'm hesitant to merge them in since I don't think it handles all cases well. 

Some cases include:
* Handling other transport types from `compressed`
* Handling cases where the raw transport type is not published, and only a specific transport type is being published. Although this is unusual, it seems many people do this if the camera straight up provides a compressed image.
* Handling cases where a topic ends with a transport type, but isn't an image topic. (eg. a topic `/text/compressed (std_msgs/msg/String)`. We shouldn't list this in the combobox.)

In regards to the last case, the difficulty in verifying the message type, is that there seems to be no easy way of listing all image transport msg types (in a similar way as listing all transport types using `image_transport::getDeclaredTransports()`).

I'm investigating on [ijnek/jinek-image-topics](https://github.com/ijnek/rqt_image_overlay/tree/ijnek-image-topics), which has some tests that handles the cases listed above, in case you're interested. I'd like to investigate this further tomorrow to see if it's possible to handle all cases above.

Happy to discuss thoughts/concerns.

**Comment by wep21** [comment]
> I think we should use brackets or separate by space, rather than a slash. ComboBox items could look like:

In my opinion, we can recognize the transport type by the image topic name, so we don't have to separate them in the combo box.

**Comment by wep21** [comment]
> Handling other transport types from compressed

image
We can select the topic which has `compressedDepth` transport. The image isn't shown in the viewer with the error below, but I guess this is the issue of `comppressed_depth_image_transport`, which does not block this PR.
`[ERROR] [1645373148.367592280] [compressed_depth_image_transport]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: rgb8).`

**Comment by wep21** [comment]
> Handling cases where a topic ends with a transport type, but isn't an image topic. (eg. a topic /text/compressed (std_msgs/msg/String). We shouldn't list this in the combobox.)

`ListImageTopics` only searches for topics which has `CompressedImage` type, so I don't think this is a problem.
https://github.com/wep21/rqt_image_overlay/blob/34111023d35d7e8f900ae53433225dc36c81acec/rqt_image_overlay/src/list_image_topics.cpp#L34

**Comment by wep21** [comment]
> Handling cases where the raw transport type is not published, and only a specific transport type is being published. Although this is unusual, it seems many people do this if the camera straight up provides a compressed image.

I have not tested this case yet, so I will try to test it.

**Comment by ijnek** [comment]
> `ListImageTopics` only searches for topics which has `CompressedImage` type, so I don't think this is a problem. https://github.com/wep21/rqt_image_overlay/blob/34111023d35d7e8f900ae53433225dc36c81acec/rqt_image_overlay/src/list_image_topics.cpp#L34

I get that this is just ported from rqt_image_view, but why should the "compressed" image transport format be dealt exclusively? The code should be generalised to handle all available transports, not just compressed.

**Comment by ijnek** [comment]
> > Handling other transport types from compressed
> 
> image We can select the topic which has `compressedDepth` transport. The image isn't shown in the viewer with the error below, but I guess this is the issue of `comppressed_depth_image_transport`, which does not block this PR. `[ERROR] [1645373148.367592280] [compressed_depth_image_transport]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: rgb8).`

Yep, I think we can safely ignore comppressed_depth_image_transport.

**Comment by ijnek** [comment]
I really do appreciate your contributions, thanks @wep21 !

Superceded by #9 and #10.

> Handling other transport types from compressed
> Handling cases where the raw transport type is not published, and only a specific transport type is being published. Although this is unusual, it seems many people do this if the camera straight up provides a compressed image.

These are handled by the image topic detection in #10, and proved with tests.

> Handling cases where a topic ends with a transport type, but isn't an image topic. (eg. a topic /text/compressed (std_msgs/msg/String). We shouldn't list this in the combobox.)

Handled in #11.

If there are further issues, please open in a new issue or PR!

**Comment by wep21** [comment]
@ijnek Thank you for the re-implementation! I appreciate it if you could release these changes to `rolling` and `galactic`.

**Comment by ijnek** [comment]
Sure, opened release PRs in [galactic](https://github.com/ros/rosdistro/pull/32304) and [rolling](https://github.com/ros/rosdistro/pull/32305).

**Pull request closed without merging**
